<?php
// +----------------------------------------------------------------------
// | Created by PHPstorm: [ JRK丶Admin ]
// +----------------------------------------------------------------------
// | Copyright (c) 2019~2022 [LuckyHHY] All rights reserved.
// +----------------------------------------------------------------------
// | SiteUrl: http://www.luckyhhy.cn
// +----------------------------------------------------------------------
// | Author: LuckyHhy <jackhhy520@qq.com>
// +----------------------------------------------------------------------
// | Date: 2020/6/26 0026
// +----------------------------------------------------------------------
// | Description:  
// +----------------------------------------------------------------------

namespace app\index\controller;


use think\exception\Handle;
use think\exception\ValidateException;
use think\Response;
use Throwable;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\exception\HttpException;
use think\exception\HttpResponseException;

/**
 * Class AdminException
 * @package app\admin\controller\
 * 后台异常类处理
 */
class IndexException extends Handle
{

    /**
     * 不需要记录信息（日志）的异常类列表
     * @var array
     */
    protected $ignoreReport = [
        HttpException::class,
        HttpResponseException::class,
        ModelNotFoundException::class,
        DataNotFoundException::class,
        ValidateException::class,
    ];



    /**
     * 记录异常信息（包括日志或者其它方式记录）
     *
     * @access public
     * @param  Throwable $exception
     * @return void
     */
    public function report(Throwable $exception): void
    {
        // 使用内置的方式记录异常日志
        parent::report($exception);
    }




    public function render($request, Throwable $e): Response
    {
        /**
         * 参数验证错误
         */
        if ($e instanceof ValidateException) {
            return json($e->getError(),0);
        }
        if ($e instanceof \Exception && request()->isAjax()) {
            return json(['code' => $e->getCode(), 'msg' => $e->getMessage(), 'data' => $e->getFile()],0);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }




}