<?php

namespace app\index\controller;

use app\BaseController;
use app\common\controller\IndexBaseController;

class Index extends IndexBaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        return  $this->fetch();
    }

}
