<?php
// +----------------------------------------------------------------------
// | Created by PHPstorm: [ JRK丶Admin ]
// +----------------------------------------------------------------------
// | Copyright (c) 2019~2022 [LuckyHHY] All rights reserved.
// +----------------------------------------------------------------------
// | SiteUrl: http://www.luckyhhy.cn
// +----------------------------------------------------------------------
// | Author: LuckyHhy <jackhhy520@qq.com>
// +----------------------------------------------------------------------
// | Date: 2020/6/26 0026
// +----------------------------------------------------------------------
// | Description:
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\model\AttachMent;
use app\common\controller\AdminBaseController;
use Jrk\Zipdown;
use think\facade\Db;

class AttachMents extends AdminBaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model=new AttachMent();

        //附件类型
        $type=$this->model->field("type")->group("type")->select()->toArray();
        $this->assign("type",$type);
    }


    /**
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:上传附件
     */
    public function uploadAttachment(){
       return $this->fetch("upattachment");
    }


    /**
     * @return string
     * @throws \Exception
     * @author: LuckyHhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:获取图片附件
     */
    public function getImages(){
        $res=$this->model->GetImagesFiles();
        $this->assign('data', $res->toArray());
        $this->assign('page', $res->render());
        return $this->fetch();
    }



    /**
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:打包下载
     */
    public function download(){
      $id= $this->request->param("id");
        if (is_array($id)){
            $ids=$id;
        }else{
            $ids=@explode(",",$id);
        }
        $data=$this->model->where('id', 'in',$ids)->select()->toArray();

        if (empty($data)) {
            $this->error("暂无数据");
        }
        //dd($data);

        //实例化下载类
        $down=new Zipdown();
        //产生一个临时文件
        $dfile = tempnam(sys_get_temp_dir(), 'tmp');
        // 最终生成的文件名（含路径）
        $filename =date ( 'YmdHis' ) . ".zip";
        foreach($data as $k=>$val){
            if(file_exists(app()->getRootPath().'public'.$val['att_dir'])){
                $down->add_file(file_get_contents(app()->getRootPath().'public'.$val['att_dir']), iconv('UTF-8','gbk',$val['img_dir'].'/'.$val['name']));
            }
        }
        $down->output($dfile);
        ob_clean();
        header('Pragma: public');
        header('Last-Modified:'.gmdate('D, d M Y H:i:s') . 'GMT');
        header('Cache-Control:no-store, no-cache, must-revalidate');
        header('Cache-Control:pre-check=0, post-check=0, max-age=0');
        header('Content-Transfer-Encoding:binary');
        header('Content-Encoding:none');
        header('Content-type:multipart/form-data');
        header('Content-Disposition:attachment; filename="'.$filename.'"'); //设置下载的默认文件名
        header('Content-length:'. filesize($dfile));
        $fp = fopen($dfile, 'r');
        while(connection_status() == 0 && $buf = @fread($fp, 8192)){
            echo $buf;
        }
        fclose($fp);
        @unlink($dfile);
        @flush();
        @ob_flush();
        ob_end_clean();
        exit();
        //打包下载结束
    }



}