<?php
// +----------------------------------------------------------------------
// | Created by PHPstorm: [ JRK丶Admin ]
// +----------------------------------------------------------------------
// | Copyright (c) 2019~2022 [LuckyHHY] All rights reserved.
// +----------------------------------------------------------------------
// | SiteUrl: http://www.luckyhhy.cn
// +----------------------------------------------------------------------
// | Author: LuckyHhy <jackhhy520@qq.com>
// +----------------------------------------------------------------------
// | Date: 2020/6/27 0027
// +----------------------------------------------------------------------
// | Description:  
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\model\AttachMent;
use app\admin\service\UploadFileService;
use app\common\controller\AdminBaseController;
use Jrk\Tool;
use think\facade\Db;

class Common extends AdminBaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return \think\response\Json
     * @author: LuckyHhy <jackhhy520@qq.com>
     * @date: 2020/6/27 0027
     * @describe:
     */
    public function changeStatus()
    {
        if (IS_POST) {
            try {
                $data = $this->request->post();
                if (empty($data['table'])) {
                    return parent::JsonReturn("表名不能为空", 0);
                }
                $table = $data['table'] ? $data['table'] : "";
                $res = Db::name("{$table}")->where(["id" => (int)$data['id']])->update([$data['field'] => $data['status']]);
                if ($res !== false) {
                    return parent::JsonReturn("操作成功");
                } else {
                    return parent::JsonReturn("操作失败", 0);
                }

            } catch (\Exception $exception) {
                return parent::JsonReturn($exception->getMessage(), 0);
            }
        }
    }


    /**
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/6/30 0030
     * @describe:头像上传
     */
    public function UpImg(){
        $ok= self::UpImages("adminuser/avatar");
        if (is_array($ok)){
            return parent::JsonReturn("上传成功",1,'',$ok);
        }else{
            return parent::JsonReturn($ok,0);
        }
    }


    /**
     * @return array|false|string|\think\response\Json
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:webupload上传素材图片
     */
    public function upWebupload(){
        $res= self::UpImages("attachment/images");
        if (is_array($res)){
            return json_encode($res['dir']);
        }else{
            return $res;
        }
    }


    /**
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:上传文件
     */
    public function UpFile(){
       $file= self::UpFiles("attachment/files");
        if ($file["status"]==true){
            return parent::JsonReturn("上传成功",1,'',$file);
        }else{
            return ['code' => 0, 'msg' => '上传失败'];
        }
    }


    /**
     * @param $path  //保存的路径
     * @param int $is_save  是否保存到数据库
     * @param string $fileName
     * @return \think\response\Json
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/6/30 0030
     * @describe:公共图片上传方法
     */
    protected static function UpImages($path,$is_save=1,$fileName="file"){
        if (empty($path)) $path="common/images";
        $res= UploadFileService::instance()->setUploadPath($path)->image($fileName);
        if (is_array($res)){
             if ($is_save==1){
                 AttachMent::attachmentAdd($res['name'],$res['size'],$res['type'],$res['dir'],$res['thumb_path'],$res['image_type'],$path,$res['ext']);
             }
        }
         return $res;
    }


    /**
     * @param $path
     * @param int $is_save
     * @param string $fileName
     * @return mixed|object
     * @author: Hhy <jackhhy520@qq.com>
     * @date: 2020/7/2 0002
     * @describe:上传附件
     */
    protected static function UpFiles($path,$is_save=1,$fileName="file"){
        if (empty($path)) $path="common/files";
        $res=UploadFileService::instance()->setUploadPath($path)->file($fileName);
        $res=Tool::object_to_array($res);
        if ($res["status"]==true){
            if ($is_save==1){
                AttachMent::attachmentAdd($res['name'],$res['size'],$res['type'],$res['dir'],$res['thumb_path'],$res['image_type'],$path,$res['ext']);
            }
        }
        return $res;
    }





}